### ISSUE TITLE
Grainflow Loads w/ 100% CPU Usage

### ISSUE THREAD

**Issue by j4ustin** [composingcap/grainflow#17]
Grainflow loaded into an empty patcher eats up > 100% of my CPU. Causes clipping, and crashes Max if closed while the Audio Engine is running. Image attached. System info: 

Max Version: 8.3.2
OS: Windows 11 Pro 
CPU: AMD Ryzen 9 3900X 
RAM: 32GB

![image](https://user-images.githubusercontent.com/1849385/190694913-c9c4ff1b-4f28-40d4-afbe-23583cf949bd.png)

**Comment by composingcap** [comment]
It is running poorly because of the low signal vector size. Max in general
runs pretty poorly at signal vector sizes below 256 in my experience,
though you can get away with something like 64 samples of you are not doing
much. It really is not designed to have a sv size of 2 though. Grainflow is
also a bit heavy, but your cpu should be able to handle it fine.

**Comment by j4ustin** [comment]
Woops! Thanks for the tip
